In [4]:
import numpy as np
x=np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [70]:
a=np.arange(5)
y=np.zeros(10)
c=np.power(2,a, out=y[::2])
c

array([ 1.,  2.,  4.,  8., 16.])

In [41]:
a=np.arange(3).reshape((3,1))
b=np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [57]:
theta = np.linspace(0, np.pi, 3) 
theta


array([0.        , 1.57079633, 3.14159265])

In [43]:
M=np.ones([3,2])
a=np.arange(3)

In [48]:
x=np.random.random((10,3))
xmean=x.mean(0)
xmean

array([0.62193282, 0.37803238, 0.56094248])

In [50]:
centered=x-xmean
centered

array([[-0.39876063, -0.01472335,  0.37277882],
       [ 0.13206519,  0.263396  , -0.41048129],
       [-0.33883399, -0.19108557,  0.22305803],
       [ 0.35962933, -0.36710402,  0.05601049],
       [ 0.24228105,  0.01948234, -0.43068855],
       [ 0.0725017 ,  0.17640925, -0.42280193],
       [-0.05733571,  0.274869  , -0.12390007],
       [-0.09284421,  0.24733681,  0.43340043],
       [ 0.27957309, -0.25731166,  0.34505586],
       [-0.19827582, -0.15126881, -0.04243178]])

In [52]:
centered.mean(0)

array([-2.22044605e-17, -2.22044605e-17,  0.00000000e+00])

In [6]:
import numpy as np
import statsmodels.api as sm
predictors=np.random.random(1000).reshape(500,2)
target=predictors.dot(np.array([0.4,0.6]))+np.random.random(500)
lmRegModel=sm.OLS(target,predictors)#подбор линейной регрессии для данных
result=lmRegModel.fit()#подбор линейной регрессии для данных
a=result.summary()#вывод статистики соответствия модели
a

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.888
Model:                            OLS   Adj. R-squared:                  0.888
Method:                 Least Squares   F-statistic:                     1977.
Date:                Mon, 23 Apr 2018   Prob (F-statistic):          1.32e-237
Time:                        20:59:02   Log-Likelihood:                -188.29
No. Observations:                 500   AIC:                             380.6
Df Residuals:                     498   BIC:                             389.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.8329      0.041     20.263      0.000       0.752       0.914
x2             0.9938      0.041     24.442      0.000       0.914       1.074
==============================================================================
Omnibus:                       44.403   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               14.326
Skew:                          -0.010   Prob(JB):                     0.000775
Kurtosis:                       2.171   Cond. No.                         2.63
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
from sklearn import neighbors
import numpy as np
predictors=np.random.random(1000).reshape(500,2)
target=np.around(predictors.dot(np.array([0.4,0.6]))+np.random.random(500))#создание случайных свободных данных и плуслучайных целевых данных на основании свободных, around окргуляет до ближайшего целого
clf=neighbors.KNeighborsClassifier(n_neighbors=10)#классификация по модели 10 ближайших соседей
knn=clf.fit(predictors,target)
knn.score(predictors,target)#получение метрики соответсвия модели, какой процент классификации был правильным
a=knn.predict(predictors)